---
version: 1
disable_existing_loggers: True

formatters:
  simple:
    format: "[%(asctime)s.%(msecs)03d %(levelname)-8s %(module)-15s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /var/log/sawtooth/gaiachain-debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8


loggers:
  gaiachain_cli:
    level: DEBUG
    handlers: [console]

root:
  level: INFO
