# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import agent_pb2 as agent__pb2
from . import entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='gaiachain',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rpayload.proto\x12\tgaiachain\x1a\x0b\x61gent.proto\x1a\x0c\x65ntity.proto\"\x8e\x03\n\tSCPayload\x12+\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1b.gaiachain.SCPayload.Action\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x32\n\x0c\x63reate_agent\x18\x03 \x01(\x0b\x32\x1c.gaiachain.CreateAgentAction\x12\x36\n\x0e\x63reate_package\x18\x04 \x01(\x0b\x32\x1e.gaiachain.CreatePackageAction\x12\x36\n\x0eupdate_package\x18\x05 \x01(\x0b\x32\x1e.gaiachain.UpdatePackageAction\x12@\n\x13\x63reate_replantation\x18\x06 \x01(\x0b\x32#.gaiachain.CreateReplantationAction\"[\n\x06\x41\x63tion\x12\x10\n\x0c\x43REATE_AGENT\x10\x00\x12\x12\n\x0e\x43REATE_PACKAGE\x10\x01\x12\x12\n\x0eUPDATE_PACKAGE\x10\x02\x12\x17\n\x13\x43REATE_REPLANTATION\x10\x03\"4\n\x11\x43reateAgentAction\x12\x1f\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x10.gaiachain.Agent\":\n\x13\x43reatePackageAction\x12#\n\x07package\x18\x01 \x01(\x0b\x32\x12.gaiachain.Package\"D\n\x13UpdatePackageAction\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x11.gaiachain.Entity\"I\n\x18\x43reateReplantationAction\x12-\n\x0creplantation\x18\x01 \x01(\x0b\x32\x17.gaiachain.Replantationb\x06proto3'
  ,
  dependencies=[agent__pb2.DESCRIPTOR,entity__pb2.DESCRIPTOR,])



_SCPAYLOAD_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='gaiachain.SCPayload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_AGENT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_PACKAGE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_PACKAGE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_REPLANTATION', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=363,
  serialized_end=454,
)
_sym_db.RegisterEnumDescriptor(_SCPAYLOAD_ACTION)


_SCPAYLOAD = _descriptor.Descriptor(
  name='SCPayload',
  full_name='gaiachain.SCPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='gaiachain.SCPayload.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='gaiachain.SCPayload.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_agent', full_name='gaiachain.SCPayload.create_agent', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_package', full_name='gaiachain.SCPayload.create_package', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_package', full_name='gaiachain.SCPayload.update_package', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_replantation', full_name='gaiachain.SCPayload.create_replantation', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SCPAYLOAD_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=454,
)


_CREATEAGENTACTION = _descriptor.Descriptor(
  name='CreateAgentAction',
  full_name='gaiachain.CreateAgentAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent', full_name='gaiachain.CreateAgentAction.agent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=508,
)


_CREATEPACKAGEACTION = _descriptor.Descriptor(
  name='CreatePackageAction',
  full_name='gaiachain.CreatePackageAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package', full_name='gaiachain.CreatePackageAction.package', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=568,
)


_UPDATEPACKAGEACTION = _descriptor.Descriptor(
  name='UpdatePackageAction',
  full_name='gaiachain.UpdatePackageAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gaiachain.UpdatePackageAction.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity', full_name='gaiachain.UpdatePackageAction.entity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=638,
)


_CREATEREPLANTATIONACTION = _descriptor.Descriptor(
  name='CreateReplantationAction',
  full_name='gaiachain.CreateReplantationAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replantation', full_name='gaiachain.CreateReplantationAction.replantation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=713,
)

_SCPAYLOAD.fields_by_name['action'].enum_type = _SCPAYLOAD_ACTION
_SCPAYLOAD.fields_by_name['create_agent'].message_type = _CREATEAGENTACTION
_SCPAYLOAD.fields_by_name['create_package'].message_type = _CREATEPACKAGEACTION
_SCPAYLOAD.fields_by_name['update_package'].message_type = _UPDATEPACKAGEACTION
_SCPAYLOAD.fields_by_name['create_replantation'].message_type = _CREATEREPLANTATIONACTION
_SCPAYLOAD_ACTION.containing_type = _SCPAYLOAD
_CREATEAGENTACTION.fields_by_name['agent'].message_type = agent__pb2._AGENT
_CREATEPACKAGEACTION.fields_by_name['package'].message_type = entity__pb2._PACKAGE
_UPDATEPACKAGEACTION.fields_by_name['entity'].message_type = entity__pb2._ENTITY
_CREATEREPLANTATIONACTION.fields_by_name['replantation'].message_type = entity__pb2._REPLANTATION
DESCRIPTOR.message_types_by_name['SCPayload'] = _SCPAYLOAD
DESCRIPTOR.message_types_by_name['CreateAgentAction'] = _CREATEAGENTACTION
DESCRIPTOR.message_types_by_name['CreatePackageAction'] = _CREATEPACKAGEACTION
DESCRIPTOR.message_types_by_name['UpdatePackageAction'] = _UPDATEPACKAGEACTION
DESCRIPTOR.message_types_by_name['CreateReplantationAction'] = _CREATEREPLANTATIONACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SCPayload = _reflection.GeneratedProtocolMessageType('SCPayload', (_message.Message,), {
  'DESCRIPTOR' : _SCPAYLOAD,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:gaiachain.SCPayload)
  })
_sym_db.RegisterMessage(SCPayload)

CreateAgentAction = _reflection.GeneratedProtocolMessageType('CreateAgentAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATEAGENTACTION,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:gaiachain.CreateAgentAction)
  })
_sym_db.RegisterMessage(CreateAgentAction)

CreatePackageAction = _reflection.GeneratedProtocolMessageType('CreatePackageAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPACKAGEACTION,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:gaiachain.CreatePackageAction)
  })
_sym_db.RegisterMessage(CreatePackageAction)

UpdatePackageAction = _reflection.GeneratedProtocolMessageType('UpdatePackageAction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPACKAGEACTION,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:gaiachain.UpdatePackageAction)
  })
_sym_db.RegisterMessage(UpdatePackageAction)

CreateReplantationAction = _reflection.GeneratedProtocolMessageType('CreateReplantationAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREPLANTATIONACTION,
  '__module__' : 'payload_pb2'
  # @@protoc_insertion_point(class_scope:gaiachain.CreateReplantationAction)
  })
_sym_db.RegisterMessage(CreateReplantationAction)


# @@protoc_insertion_point(module_scope)
