# Generated by Django 2.2.7 on 2020-05-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200528_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oven',
            name='carbonization_ending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ovens', to='entities.CarbonizationEnding', verbose_name='Carbonization Ending'),
        ),
    ]
