# Generated by Django 2.2.7 on 2020-06-03 11:51

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additional_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0003_auto_20200528_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replantation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trees_planted', models.PositiveIntegerField(verbose_name='Number of trees planted')),
                ('beginning_date', models.PositiveIntegerField(verbose_name='Beginning date')),
                ('ending_date', models.PositiveIntegerField(verbose_name='Ending date')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replantations', to='entities.Package', verbose_name='Plot ID')),
                ('tree_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additional_data.TreeSpecie', verbose_name='Tree specie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replantations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
