# Generated by Django 2.2.7 on 2020-06-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_replantation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replantation',
            name='plot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replantation', to='entities.Package', verbose_name='Plot ID'),
        ),
    ]
