# Generated by Django 2.2.7 on 2020-06-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_package_blockchain_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='replantation',
            name='blockchain_batch_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Blockchain Batch ID'),
        ),
    ]
