# Generated by Django 2.2.7 on 2020-06-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_reception_reception_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oven',
            name='carbonization_ending',
        ),
        migrations.AddField(
            model_name='carbonizationending',
            name='oven',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carbonization_ending', to='entities.Oven', verbose_name='Oven'),
        ),
    ]
