# Generated by Django 2.2.7 on 2020-07-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_auto_20200625_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Is Finished'),
        ),
    ]
