# Generated by Django 2.2.7 on 2020-07-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_package_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonizationbeginning',
            name='oven_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbonization_beginnings', to='additional_data.OvenType', verbose_name='Oven type'),
        ),
        migrations.AlterField(
            model_name='loggingbeginning',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_loggings', to='additional_data.Parcel', verbose_name='Parcel'),
        ),
    ]
