# Generated by Django 2.2.7 on 2020-08-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20200717_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonizationbeginning',
            name='oven_height2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Oven height 2'),
        ),
        migrations.AddField(
            model_name='carbonizationbeginning',
            name='oven_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Oven volume'),
        ),
    ]
