# Generated by Django 2.2.7 on 2020-09-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20200804_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Local'), (2, 'Final')], default=2, verbose_name='Type'),
        ),
    ]
