---
version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "[%(asctime)s.%(msecs)03d %(levelname)-8s %(module)-15s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: /var/log/sawtooth/gaiachain-info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /var/log/sawtooth/gaiachain-debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: simple
    filename: /var/log/sawtooth/gaiachain-error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

#loggers:
#  processor:
#    level: DEBUG
#    handlers: [console]

root:
  level: DEBUG
  handlers: [console, debug_file_handler, info_file_handler, error_file_handler]
