# Generated by Django 2.2.7 on 2020-07-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_data', '0002_oventype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='oventype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Parcel code'),
        ),
        migrations.AlterField(
            model_name='treespecie',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Village name'),
        ),
    ]
