# Generated by Django 2.2.7 on 2020-08-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_data', '0004_auto_20200722_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='oventype',
            name='oven_height2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Oven height2'),
        ),
    ]
